microsoft/Conversation-Knowledge-Mining-Solution-Accelerator

infrastructure/ARM/deployment-template.json
updated the facetable values from False to True for custom fields so the custom fields will be displayed in the Filter list in the UI
=> Issue# 1811: Update Facetable True/False values for custom fields

README.md
- Updates the "Deploy to Azure button" target ensuring it deploys using the updated production code ARM template introduced in PR #28.
- Reference Issue # 1811 and Internal Bug # 1853.
=> Fixes Azure deployment link with updated ARM template path

README.md, infrastructure/ARM/deployment-template.json
Updated the deploy button reference link in the readme file to point to the master branch.
Updated the OpenAI prompt parameter in the deployment template file
=> Bug-1847/1854: Update deploy button reference link and OpenAI prompt in the deployment template

README.md, infrastructure/ARM/deployment-template.json
updated the container registry name and update the Facetable value for the Summary field.
=> Update Deployment Template

GBB.ConversationalKM.WebUI/CognitiveSearch.UI/wwwroot/js/entityMap.js, GBB.ConversationalKM.WebUI/CognitiveSearch.UI/wwwroot/js/facets.js
Updated UI to resolve Bugs 1933 and 1936
=> Resolve Bugs 1933 and 1936

GBB.ConversationalKM.WebUI/CognitiveSearch.UI/wwwroot/js/details.js
Removes the final row in the metadata table. Repairs internal Bug # 1937 per consultation with eng & design.
=> Update details.js with metadata page update

README.md, infrastructure/ARM/deployment-template.json
Updated the deployment template to remove parameter that is no longer needed due to recent changes to the Cognitive Search Service Speech SDK
=> Removes Deployment Blocker by addressing the Cognitive Search Service Speech dependency changes 

infrastructure/ARM/deployment-template.json
Updated the deployment template to accommodate the changes to the cognitive services speech sdk.
=> AB#2321 Resolve deployment issues due to dependent services 

GBB.ConversationalKM.Python/build-search-infra/infrastructure/audio-skillset.json, GBB.ConversationalKM.Python/build-search-infra/infrastructure/sample-skillset.json, GBB.ConversationalKM.WebUI/CognitiveSearch.UI/Views/Admin/UploadData.cshtml
Added maxKeyPhraseCount = 10 in sample.skillset.json file
=> fix: keyphrases value set to 10

Deployment/bicep/main.bicep, Deployment/bicep/main.json
Bug # 4932 - remove hard-coded references.
=> Update deployment template to remove references and comments

README.md
Bug 4984: Bug - README - Update or remove "When to use this repo", pending content from Adwitia
=> Remove "When to use this repo" section from README

README.md
AB#5039: Create v1 retirement messaging on v2 branch
=> Update README.md with retirement messaging

Extensibility.md
We have updated 1 occurrences in Extensibility.md file for [Change Azure Cognitive Search --> Azure AI Search]
=> Update Extensibility.md for Update [Change Azure Cognitive Search --> Azure AI Search]

README.md, infrastructure/ARM/deployment-template.json
Updated Deployment URL for CKM-V1 in README.md
=> Update README.md for Deployment URL and branch name update in ARM Template for CKM v1

dataset/SampleConversations 1.zip
Dataset format was incorrect and updated the correct files.
=> dataset updated with proper format

infrastructure/ARM/deployment-template.json
Fix for ckmv1 accelerator deplyment failure
=> Fix for ckmv1 accelerator deplyment failure

.github/CODEOWNERS
Update CODEOWNERS for adding more code owners
=> chore: Update CODEOWNERS for adding more code owners

App/frontend/.npmrc
=> fix: removed npmrc registry

.github/workflows/deploy.yml
* This pull request includes a change to the deployment workflow configuration. The most important change is the modification of the branch name and workflow name to reflect the new version.
Changes to deployment workflow:
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L1-R5): Updated the workflow name to `CI-Validate Deployment-CKM-V2` and changed the branch from `main` to `ckm-v2` for deployment validation.
* ...
=> ci: change to the deployment workflow configuration for CKM V2

App/frontend/.npmrc
=> fix: reverted npmrc file changes 

README.md, azure.yaml
=> deployment link changed

infra/main.bicep, infra/main.json, infra/scripts/copy_kb_files.sh, infra/scripts/index_scripts/03_cu_process_data_text.py, infra/scripts/index_scripts/requirements.txt, infra/scripts/run_create_index_scripts.sh
Update missing script path in deployment scripts
=> fix: Update missing script path in deployment scripts

.github/workflows/azure-dev-validation.yml
=> template evaluation

.coveragerc, .flake8, .github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml, .github/workflows/deploy-KMGeneric.yml, .github/workflows/deploy.yml, .github/workflows/docker-build.yml, .github/workflows/pylint.yml, .github/workflows/test.yml, Deployment/bicep/deploy_app_service.bicep, Deployment/bicep/deploy_azure_function_charts.bicep, Deployment/bicep/deploy_azure_function_rag.bicep, Deployment/bicep/main.bicep, Deployment/bicep/main.bicepparam, Deployment/bicep/main.json
The purpose of this PR is to:
Enhance CI/CD Workflows:
Introduce parameterization and dynamic configuration to streamline deployment processes.
Automate Docker image builds and versioned deployments across environments.
Improve Code Quality and Maintainability:
Enforce linting and test coverage standards using .flake8 and .coveragerc.
Introduce a standardized PR template for consistent reviews.
Streamline Dependency Management:
Leverage Dependabot for automated updates, reducing manual effort and improving reliability.
Increase Collaboration Efficiency:
Update CODEOWNERS to ensure comprehensive code reviews by including additional reviewers.
Enable Flexible Deployment:
Replace hardcoded Docker image tags with the imageTag parameter for better version control and CI/CD integration.
=> ci: Add configuration files and workflows for enhanced CI/CD and quality checks

README.md
Update README.md tenant permission
* ...
=> docs: Update README.md tenant permission

README.md, infra/deploy_app_service.bicep, infra/deploy_azure_function_charts.bicep, infra/deploy_azure_function_urls.bicep, infra/deploy_storage_account.bicep, infra/main.bicep, infra/main.bicepparam
=> fix: updated deployment files

infra/deploy_azure_function_rag.bicep, infra/deploy_storage_account.bicep, infra/main.bicep, infra/main.json
=> fix: arm template changes for unique id

.github/workflows/deploy.yml, .github/workflows/pr-title-checker.yml, .github/workflows/stale-bot.yml
This pull request includes updates to the naming conventions in several GitHub workflow files to improve clarity and consistency.
Changes to workflow file names:
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L1-R1): Updated the workflow name to "Validate Deployment - CKM V2" for better readability.
* [`.github/workflows/pr-title-checker.yml`](diffhunk://#diff-3a8865ff9962bd48d45f69c2cc23f0151fc5d7512150713996f86cb21309944fL1-R1): Changed the workflow name to "PR Title Checker" to follow a consistent naming pattern.
* [`.github/workflows/stale-bot.yml`](diffhunk://#diff-7d98caa1d6d6648f3266503a806c5b7dc6214839a1a1fabd7dcaa5c54d72222eL1-R1): Renamed the workflow to "Stale Bot" for a more concise and clear description. …
=> chore: Updated Workflow Names

.github/workflows/bicep_deploy.yml, .github/workflows/deploy-KMGeneric.yml, .github/workflows/docker-build.yml, .github/workflows/pr-title-checker.yml, .github/workflows/pylint.yml, .github/workflows/stale-bot.yml, .github/workflows/test.yml
This pull request includes several changes to various GitHub workflow files to standardize naming conventions and update schedules. The most important changes include renaming workflow jobs for clarity and modifying the schedule for the deployment workflow.
Renaming workflow jobs for clarity:
* [`.github/workflows/bicep_deploy.yml`](diffhunk://#diff-4007e2f15e5934589e8adb09b8fcd77105c83c9f7483c13fede1ef1aa080736aL1-R1): Renamed job to "Validate Deployment - CKM V2"
* [`.github/workflows/deploy-KMGeneric.yml`](diffhunk://#diff-d89c1a2a54c3fecc22cbfae6dc62ebdfeb753cd82c7192b447c07e8235242d75L1-R1): Renamed job to "Validate Deployment - KM Generic"
* [`.github/workflows/docker-build.yml`](diffhunk://#diff-3414847e2ad632333f775cabb810f0dc0df61a570365df34750a08b00912fe82L1-R1): Renamed job to …
=> chore: Updated workflow names and trigger schedule

.github/workflows/deploy-KMGeneric.yml
* This pull request includes a change to the deployment workflow file to update the path to the Bicep template file. 
Deployment workflow update:
* [`.github/workflows/deploy-KMGeneric.yml`](diffhunk://#diff-d89c1a2a54c3fecc22cbfae6dc62ebdfeb753cd82c7192b447c07e8235242d75L68-R68): Changed the `--template-file` path from `Deployment/bicep/main.bicep` to `infra/main.bicep`.
* ...
=> ci: Deployment workflow update

.github/workflows/docker-build.yml
This pull request includes changes to the `.github/workflows/docker-build.yml` file to add support for a new branch named `dependabotchanges`. The most important changes include updating the conditions for Azure Container Registry login, determining the tag name, and pushing Docker images.
Changes to support the `dependabotchanges` branch:
* Updated the condition for logging in to Azure Container Registry to include the `dependabotchanges` branch for both `push` and `workflow_dispatch` events. (`[.github/workflows/docker-build.ymlL33-R33](diffhunk://#diff-3414847e2ad632333f775cabb810f0dc0df61a570365df34750a08b00912fe82L33-R33)`)
* Added logic to set the tag name to `dependabotchanges` when the branch name is `dependabotchanges`. (`[.github/workflows/docker-build.ymlR57-R58](diffhunk://#dif …
=> ci: Extend Docker Build Workflow to Support dependabotchanges Branch

README.md
Bugs:
https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/14473/
=> fix: Updated readme file

infra/deploy_ai_foundry.bicep, infra/deploy_azure_function_charts.bicep, infra/deploy_azure_function_rag.bicep, infra/deploy_storage_account.bicep
* To enhance security by disabling shared key access for storage accounts.
* ...
=> fix: storage permission issue

.github/workflows/deploy-KMGeneric.yml, README.md, infra/deploy_ai_foundry.bicep, infra/deploy_azure_function_charts.bicep, infra/deploy_azure_function_rag.bicep, infra/deploy_storage_account.bicep, infra/main.json
* Updated readme file for better understanding
* Resolved deployment issue store storage accounts for permission issue.
* ...
=> fix: Readme file update and Storage policy issue

README.md, azure.yaml
=> docs: update the readme deployment

.github/workflows/deploy-KMGeneric.yml
This pull request includes several changes to the `deploy-KMGeneric.yml` workflow file, focusing on enhancing deployment processes, resource management, and cleanup procedures. The most important changes include adding manual workflow dispatch, updating resource group creation, improving unique solution prefix generation, refining tag determination, and adding steps for resource extraction, soft deletion, and purging.
Enhancements to deployment processes:
* Added manual workflow dispatch to trigger the workflow manually. (`.github/workflows/deploy-KMGeneric.yml`)
Resource management improvements:
* Changed the location for resource group creation from `eastus` to `eastus2`. (`.github/workflows/deploy-KMGeneric.yml`)
* Improved the unique solution prefix generation by using the last 5 …
=> ci: Update deploy-KMGeneric.yml

azure.yaml
=> fix: update yaml

README.md, azure.yaml, infra/main.bicep, infra/main.bicepparam, infra/main.json
=> fix: update yaml, readme and bicep

infra/deploy_ai_foundry.bicep, infra/deploy_app_service.bicep, infra/main.bicep, infra/main.json
* Removed duplicate application insights services.
* ...
=> fix: Removed duplicate application insights 

infra/scripts/index_scripts/03_cu_process_data_text.py
=> fix: update search index id

.github/workflows/bicep_deploy.yml, .github/workflows/deploy-KMGeneric.yml, infra/scripts/checkquota_ckmv2.sh, infra/scripts/checkquota_km.sh
* ...
This pull request introduces several changes to improve the deployment workflows by adding quota checks and dynamically setting the deployment region. The most important changes include adding quota check scripts, updating the deployment workflows to run these checks, and adjusting resource creation commands to use the selected region.
Quota Check Implementation:
* Added `infra/scripts/checkquota_ckmv2.sh` script to check for sufficient quota in specified Azure regions before proceeding with deployment.
* Added `infra/scripts/checkquota_km.sh` script to check for sufficient quota in specified Azure regions before proceeding with deployment.
Workflow Updates:
* Updated `.github/workflows/bicep_deploy.yml` to include steps for running the quota check, sending notifications on quota …
=> ci: implement quota check in CI Pipeline to ensure resource availability in supported region

.github/workflows/bicep_deploy.yml, .github/workflows/deploy-KMGeneric.yml, infra/scripts/checkquota_ckmv2.sh
* ...
This pull request includes several changes to the deployment workflows and scripts, primarily focusing on adjusting capacity settings and removing unused environment variables. The most important changes are summarized below:
* [`.github/workflows/bicep_deploy.yml`](diffhunk://#diff-4007e2f15e5934589e8adb09b8fcd77105c83c9f7483c13fede1ef1aa080736aL22-R22): Reduced `GPT_MIN_CAPACITY` from 130 to 30. Removed `TEXT_EMBEDDING_MIN_CAPACITY`.
* [`.github/workflows/deploy-KMGeneric.yml`](diffhunk://#diff-d89c1a2a54c3fecc22cbfae6dc62ebdfeb753cd82c7192b447c07e8235242d75L29-R30): Adjusted `GPT_MIN_CAPACITY` from 130 to 100 and `TEXT_EMBEDDING_MIN_CAPACITY` from 30 to 80.
* [`infra/scripts/checkquota_ckmv2.sh`](diffhunk://#diff-c8d1073afa8603fae1f98ba9700bd633fd299d5bab4326cd0ace90c450689114L8): …
=> fix: updated capacity according to bicep

README.md, infra/main.bicep, infra/main.bicepparam, infra/main.json
* Error with location for the Content Understanding service deployment by azd has been fixed.
* ...
=> fix: CU location issue fix

.github/workflows/bicep_deploy.yml, .github/workflows/deploy-KMGeneric.yml, infra/scripts/checkquota_ckmv2.sh, infra/scripts/checkquota_km.sh
Add the variables
**AZURE_REGIONS_KM** with the value: eastus2 &
**AZURE_REGIONS** with the value: northcentralus, eastus
* ...
This pull request includes changes to the Azure deployment workflows and scripts to support dynamic region configuration using environment variables. The most important changes include adding the `AZURE_REGIONS` environment variable and updating the scripts to read this variable.
Workflow updates:
* [`.github/workflows/bicep_deploy.yml`](diffhunk://#diff-4007e2f15e5934589e8adb09b8fcd77105c83c9f7483c13fede1ef1aa080736aR23): Added `AZURE_REGIONS` environment variable to the deployment job.
* [`.github/workflows/deploy-KMGeneric.yml`](diffhunk://#diff-d89c1a2a54c3fecc22cbfae6dc62ebdfeb753cd82c7192b447c07e8235242d75R31): Added `AZURE_REGIONS_KM` environment variable …
=> fix: quota check script with dynamic region handling

README.md
This pull request includes a minor change to the `README.md` file. The change corrects the URL encoding in the "Deploy to Azure" button link.
* [`README.md`]: Corrected the URL encoding in the "Deploy to Azure" button link to ensure proper redirection.
=> docs: corrects the URL encoding in the "Deploy to Azure" button link

README.md, docs/AzureSemanticSearchRegion.md
=> docs: update readme

infra/main.json
This pull request includes several changes to the `infra/main.json` file for modifying a script for creating SQL users and assigning roles.
Script modification:
* Modified the script for creating a SQL user and assigning roles to ensure that the `sp_addrolemember` procedure is executed outside the `IF NOT EXISTS` block, allowing role assignment even if the user already exists.
* ...
=> fix: Updated main.json for 1 click deployment

.github/workflows/stale-bot.yml
* Identify & List Stale Merged Branches with No Activity in Last 3 Months
* Identify & List PR Approved & Merged Branches (Older Than 30 Days)
* List Open PR Branches With No Activity in Last 3 Months
* ...
=> fix: update state-bot.yml

.github/workflows/stale-bot.yml
* Identify & List Stale Merged Branches with No Activity in Last 3 Months
* Identify & List PR Approved & Merged Branches (Older Than 30 Days)
* List Open PR Branches With No Activity in Last 3 Months
* ...
=> fix: update stale-bot.yml

infra/deploy_ai_foundry.bicep, infra/main.json
This pull request involves significant changes to the `infra/deploy_ai_foundry.bicep` and `infra/main.json` files, primarily focusing on the removal and commenting out of configurations related to the `phiserverless` model. Here are the most important changes:
* [`infra/deploy_ai_foundry.bicep`]: Commented out the `phiModelRegions` array and the `phiserverless` resource definition, including its properties and settings.
* [`infra/deploy_ai_foundry.bicep`]: Commented out the assignment of `phiserverless` properties to the `azureOpenAIInferenceEndpoint` and `azureOpenAIInferenceKey` resources, replacing their values with empty strings.
* [`infra/deploy_ai_foundry.bicep`]: Commented out the output of the `aiInfereceEndpoint` property.
* [`infra/main.json`]: Removed the `phiModelRegions`, …
=> fix:  Remove and Comment Out Phiserverless Model Configurations in Deployment Files

.github/dependabot.yml, .github/workflows/stale-bot.yml, README.md, docs/AppAuthentication.md, docs/AzureGPTQuotaSettings.md, infra/deploy_ai_foundry.bicep, infra/main.json
=> fix: Down merge from main

infra/deploy_azure_function_rag.bicep, infra/main.json, src/api/km-rag-function/function_app.py
This pull request includes several changes to the Azure Function deployment and the `function_app.py` script to support conditional use of the AI Project Client. The most important changes include adding a new environment variable, updating the deployment scripts, and modifying the code to handle the new configuration.
Updates to deployment scripts:
* [`infra/deploy_azure_function_rag.bicep`]: Added a new environment variable `USE_AI_PROJECT_CLIENT` with a default value of 'False'.
* [`infra/main.json`]: Updated the `templateHash` values to reflect the changes made in the deployment scripts. 
* [`infra/main.json`]: Added the new environment variable `USE_AI_PROJECT_CLIENT` to the configuration.
Modifications to `function_app.py`:
* [`src/api/km-rag-function/function_app.py`]: Updated the …
=> feat: Conditional use of the AI Project Client

infra/scripts/quota_check_all_regions.sh
* This pull request includes a small change to the `infra/scripts/quota_check_all_regions.sh` file. The change removes an empty line at the beginning of the script.
* ...
=> fix: Update quota_check_all_regions.sh

infra/scripts/quota_check_all_regions.sh, infra/scripts/quota_check_params.sh
* This pull request includes updates to the quota check scripts to provide users with a link to request a quota increase when there is insufficient quota. 
The most important changes include:
* [`infra/scripts/quota_check_all_regions.sh`](diffhunk://#diff-001bb1c2e81454902de60c7009d2b0c5b2aae31e1ad9a913463ee94a3f25e6acR91): Added a message with a link to request a quota increase at the end of the script.
* [`infra/scripts/quota_check_params.sh`](diffhunk://#diff-686f17dd7cf7e8af9b5575a7098de6011c9bc4b0cdc7aa3c631b66b0d5fe6975R125): Added a message with a link to request a quota increase when there is insufficient quota for a model in a region.
* ...
=> docs: helpful instructions for users to request a quota increase when necessary

infra/scripts/quota_check_params.sh
* ...
This pull request includes changes to the `infra/scripts/quota_check_params.sh` file to improve error handling and user feedback when fetching Azure subscriptions. The most important changes include adding error messages and exit conditions when no active Azure subscriptions are found.
Error handling improvements:
* Added a check for zero active Azure subscriptions and provided a clear error message with instructions to log in and ensure an active subscription.
* Added a secondary check to ensure the `AZURE_SUBSCRIPTION_ID` is not empty before proceeding, with an appropriate error message and exit condition.
Codebase cleanup:
* Added a blank line for better readability before setting the selected subscription.
No
* ...
=> fix: improvement to error handling in the script

.devcontainer/devcontainer.json
* ...
This pull request includes a small but important change to the `.devcontainer/devcontainer.json` file. The change ensures that the `quota_check_params.sh` script is executable after the container starts.
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L19-R19): Added a `chmod +x` command to the `postStartCommand` to make the `quota_check_params.sh` script executable.
No
* ...
=> feat: add permission for script in dev container

.github/workflows/create-release.yml
* Added pipeline for create release functionality. Automatically creates a release when a push is made to the main branch or when manually triggered.
* ...
=> feat: create release pipeline added

.github/workflows/create-release.yml
=> fix: Minor fix in create release

README.md, docs/PowershellSetup.md
This pull request includes changes to the `README.md` file and adds a new documentation file to help Windows users set up PowerShell 7. The most important changes include adding PowerShell as a requirement for Windows users and providing a detailed guide on how to add PowerShell 7 to the system PATH.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R138): Added PowerShell as a required tool for Windows users and included a link to the setup instructions.
* [`docs/PowershellSetup.md`](diffhunk://#diff-09969c2a1b13baf73fc808521ae353b1c74e4385f922e62a61e9a7d7fbe3967eR1-R54): Created a new file with a step-by-step guide on how to add PowerShell 7 to the PATH on Windows. This includes prerequisites, detailed steps, and troubleshooting tips. …
=> docs: add PowerShell setup guide for Windows users

.github/workflows/test.yml
This pull request includes changes to the GitHub Actions workflow configuration to update the paths for backend dependencies and test files. The most important changes are:
Workflow configuration updates:
* [`.github/workflows/test.yml`](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L77-R84): Updated the path for installing backend dependencies from `src/App/requirements.txt` to `src/api/requirements.txt`.
* [`.github/workflows/test.yml`](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L77-R84): Updated the path for checking backend test files from `src/App/backend` to `src/api`.
=> fix: Test Workflow failure

.github/dependabot.yml
This pull request includes updates to the `.github/dependabot.yml` file to modify the directory paths for dependency updates. The most important changes are:
* Changed the directory for `pip` package-ecosystem from `/App` to `/src/App`
* Changed the directory for `npm` package-ecosystem from `/App/frontend` to `/src/App/frontend`
* ...
* ...
=> chore: Update Dependabot directory paths for pip and npm ecosystems

azure.yaml
* ...
This pull request includes several updates to the infrastructure and deployment scripts, with a focus on enhancing authentication, simplifying configurations, and improving maintainability. Key changes include updates to Azure Key Vault and storage configurations, enhancements to deployment scripts for better automation, and parameterization of key scripts for flexibility.
* Removed `enablePurgeProtection` from Key Vault configurations in `infra/deploy_keyvault.bicep` and `infra/main.json` for alignment with updated security policies. [[1]](diffhunk://#diff-82312b3acfa82a4f0980d7e0592f22b8db36f98965a61c340510f972ad7306faL39) [[2]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L298)
* Commented out the `deploy_post_deployment_scripts.bicep` module …
=> fix: azure yaml provision issue

infra/scripts/checkquota_km.sh
* ...
This pull request includes a small but important update to the `infra/scripts/checkquota_km.sh` script. The change updates the model name for capacity checks to align with the correct naming convention.
* [`infra/scripts/checkquota_km.sh`](diffhunk://#diff-08eea3188bc57fa228d942aa714a2139560e674c06f1aa5dd4da391ef8326657L36-R36): Updated the model name from `OpenAI.GlobalStandard.text-embedding-ada-002` to `OpenAI.Standard.text-embedding-ada-002` in the `MIN_CAPACITY` declaration.
* ...
=> fix: validate deployment pipeline failing due to quota issue

infra/deploy_ai_foundry.bicep, infra/main.json
=> fix: update Azure AI Foundry deployment

docs/quota_check.md
Removing duplicate instructions
=> fix: Update quota_check.md

.github/workflows/docker-build.yml
* ...
This pull request updates the `.github/workflows/docker-build.yml` file to add a fallback value for the `ACR_LOGIN_SERVER` secret, ensuring the Docker image tags are generated correctly even if the secret is not set.
* Updated the `tags` field for the WebApp Docker image to use a default value (`acrlogin.azurecr.io`) for `ACR_LOGIN_SERVER` if the secret is not defined. (`[.github/workflows/docker-build.ymlL70-R71](diffhunk://#diff-3414847e2ad632333f775cabb810f0dc0df61a570365df34750a08b00912fe82L70-R71)`)
* Updated the `tags` field for the ApiApp Docker image to use a default value (`acrlogin.azurecr.io`) for `ACR_LOGIN_SERVER` if the secret is not defined. (`[.github/workflows/docker-build.ymlL80-R81](diffhunk://#diff-3414847e2ad632333f775cabb810f0dc0df61a570365df34750a08b00912fe82L8 …
=> chore: error acr tag not found

.github/workflows/docker-build.yml
* ...
This pull request updates the GitHub Actions workflow for Docker image builds, introducing a fallback value for the `ACR_LOGIN_SERVER` secret to improve reliability in case the secret is not set.
Updates to `.github/workflows/docker-build.yml`:
* Modified the `tags` field for the `WebApp` Docker image to use a fallback value (`acrloginn.azurecr.io`) for `ACR_LOGIN_SERVER` if the secret is not defined.
* Modified the `tags` field for the `ApiApp` Docker image to use the same fallback value (`acrloginn.azurecr.io`) for `ACR_LOGIN_SERVER` if the secret is not defined.
* ...
=> chore: error login server name not found

workshop/.github/workflows/deploy.yml
=> fix: Update deploy.yml

infra/deploy_sql_db.bicep, infra/main.bicep, infra/main.json
…re policies (TLS1.2 support for SQL) and increased quota for Azure AI Foundry GPT-4o deployment to avoid time outs.
SFI changes: TLS1.2 Support for SQL and Increased Quota for Azure AI GPT-4o deployment to avoid rate limiting* ...
* ...
=> fix: SFI changes: TLS1.2 Support for SQL and Increased Quota for Azure AI GPT-4o deployment to avoid rate limiting

.github/dependabot.yml, .github/workflows/Scheduled-Dependabot-PRs-Auto-Merge.yml
* Introduced a scheduled GitHub Actions workflow to auto-approve and auto-merge Dependabot PRs targeting the dependabotchanges branch.
* Also optimized the dependabot.yml configuration to group dependency updates by ecosystem and path, significantly reducing PR noise.
* ...
=> chore: dependabot poc changes

infra/scripts/add_user_scripts/create-sql-user-and-role.ps1
This pull request enhances security in the PowerShell script `create-sql-user-and-role.ps1` by improving how access tokens are handled. The changes ensure that sensitive data is securely managed in memory.
Security improvements:
* [`infra/scripts/add_user_scripts/create-sql-user-and-role.ps1`](diffhunk://#diff-db38659ac3a9761c5312f22f21d3cc6ec123558ac0bac26bbca5e66341b15b34L76-R84): Updated the handling of access tokens by using `SecureString` and converting it to plaintext only temporarily. Added a `finally` block to explicitly clear the plaintext token from memory using `ZeroFreeBSTR`, reducing the risk of sensitive data exposure.
=> fix: Use converted Secure string access token in Invoke-Sqlcmd

infra/scripts/add_user_scripts/create-sql-user-and-role.ps1
This pull request includes a security improvement in the `create-sql-user-and-role.ps1` script to handle access tokens more securely. The most important change involves using a `SecureString` to manage the access token and ensuring sensitive data is cleared from memory after use.
* [`infra/scripts/add_user_scripts/create-sql-user-and-role.ps1`](diffhunk://#diff-db38659ac3a9761c5312f22f21d3cc6ec123558ac0bac26bbca5e66341b15b34L76-R84): Updated the handling of the Azure access token by using `SecureString` and `System.Runtime.InteropServices.Marshal` to convert it to plaintext securely. Added a cleanup step to clear sensitive data from memory using `ZeroFreeBSTR`.
=> fix: Use converted secure string access token for Invoke-Sqlcmd authentication

infra/deploy_ai_foundry.bicep, infra/main.bicep, infra/main.json, src/api/api/api_routes.py, src/api/api/history_routes.py, src/api/common/logging/event_utils.py, src/api/requirements.txt
* ...
This pull request introduces changes to enhance observability by adding support for OpenTelemetry and Azure Monitor, as well as updating infrastructure outputs to include Application Insights connection strings. The most important changes are grouped by their themes below:
* Added an output for `applicationInsightsConnectionString` in `infra/deploy_ai_foundry.bicep` to expose the Application Insights connection string.
* Added an output for `APPLICATIONINSIGHTS_CONNECTION_STRING` in `infra/main.bicep` to propagate the Application Insights connection string from the AI Foundry module.
* Updated `src/api/requirements.txt` to include OpenTelemetry libraries (`opentelemetry-sdk`, `opentelemetry-api`, `opentelemetry-semantic-conventions`, `opentelemetry-instrumentation`) and Azure …
=> feat: add open telemetry logs

src/api/api/api_routes.py
* ...
This pull request updates the `src/api/api/api_routes.py` file to ensure asynchronous behavior is properly utilized in two API route functions. The changes replace synchronous calls to the `ChartService` methods with their asynchronous counterparts, improving the application's ability to handle concurrent requests.
* Updated `fetch_chart_data` to use `await chart_service.fetch_chart_data()` instead of the synchronous `chart_service.fetch_chart_data()` call.
* Updated `fetch_filter_data` to use `await chart_service.fetch_filter_data()` instead of the synchronous `chart_service.fetch_filter_data()` call.
* ...
=> fix: internal server error in fetch apis

README.md
Broken image links in KM Generic README
1. Navigate to the KM Generic repository.
2. Open the README.md file.
3. Observe the image placeholders or missing image icons.
=> fix: All images in the README should load correctly and provide visual context as intended.

README.md, docs/workshop/docs/workshop/Challenge-1/Code_Walkthrough/02_Frontend.md, docs/workshop/docs/workshop/Challenge-1/Solution_Overview.md, documents/TechnicalArchitecture.md
changed the images path in readme file
=> docs: changed the images path in readme file

docs/workshop/mkdocs.yml
=> fix: updated github page link

docs/workshop/README.md
=> refactor: more changes

documents/Fabric_deployment.md
This pull request updates the `documents/Fabric_deployment.md` file to improve clarity and usability for deploying and customizing the solution accelerator. The changes include formatting enhancements, additional notes for users with existing resources, and updates to deployment script parameters.
* Added a note in the "Create Fabric workspace" section to inform users with an existing Microsoft Fabric Workspace that they can skip workspace creation and continue from a specific step.
* Modified the description for the `workspaceid_param` in the deployment script instructions to clarify that it can refer to an existing workspace ID or one created in Step 3.
=> feat: EXP environment changes for Existing Fabric workspace

.github/workflows/deploy.yml, docs/workshop/README.md, docs/workshop/docs/workshop/Challenge-1/Code_Walkthrough/02_Frontend.md, docs/workshop/docs/workshop/Challenge-1/Solution_Overview.md, docs/workshop/docs/workshop/Challenge-5/notebooks/video_chapter_generation.ipynb, docs/workshop/docs/workshop/Challenge-5/notebooks/video_tag_generation.ipynb, docs/workshop/mkdocs.yml
=> fix: workshop doc fixes

tests/e2e-test/README.md, tests/e2e-test/pages/HomePage.py, tests/e2e-test/pytest.ini, tests/e2e-test/requirements.txt, tests/e2e-test/sample_dotenv_file.txt, tests/e2e-test/testdata/prompts.json, tests/e2e-test/tests/conftest.py, tests/e2e-test/tests/test_km_gp_tc.py
Implement Log execution time per prompt in Report for KM generic
=> test: Implemented Log execution time per prompt in Report for KM generic

documents/CustomizingAzdParameters.md, documents/DeploymentGuide.md
This pull request updates documentation files to improve clarity and add new configuration options related to Azure deployments. The changes primarily involve adjustments to default values and descriptions for Azure parameters, as well as the introduction of a new parameter for local container builds.
* [`documents/CustomizingAzdParameters.md`](diffhunk://#diff-2e319e20f66e2cd84d3764f457565dbc3fe39c15edc9d7c05801ff16c423598aL24-R25): Updated the default value for `AZURE_ENV_LOG_ANALYTICS_WORKSPACE_ID` to `<Existing Workspace Id>` and added a new parameter `USE_LOCAL_BUILD` to indicate whether to use a local container build for deployment.
* [`documents/CustomizingAzdParameters.md`](diffhunk://#diff-2e319e20f66e2cd84d3764f457565dbc3fe39c15edc9d7c05801ff16c423598aL12-R12): Removed the …
=> docs: added missing parameter in CustomizingAzdParameter.md file

.github/workflows/deploy-KMGeneric.yml
This pull request includes a small change to the `.github/workflows/deploy-KMGeneric.yml` file. The change removes the `--parameters` line from the Azure deployment command, simplifying the workflow configuration.
* ...
* ...
=> ci: Fixed deployment pipeline

.github/workflows/deploy-KMGeneric.yml
* This pull request includes a minor update to the `.github/workflows/deploy-KMGeneric.yml` file, specifically adding a new parameter to the Azure deployment command.
Deployment configuration updates:
* [`.github/workflows/deploy-KMGeneric.yml`](diffhunk://#diff-d89c1a2a54c3fecc22cbfae6dc62ebdfeb753cd82c7192b447c07e8235242d75L123-R123): Added the `aiDeploymentsLocation` parameter to the Azure deployment command, setting its value to `${{ env.AZURE_LOCATION }}`. This ensures that AI deployments are explicitly tied to the specified Azure location.
* ...
=> feat: Add aiDeploymentsLocation parameter to Bicep deployment in deploy-KMGeneric.yml

docs/workshop/docs/workshop/Challenge-1/Deployment.md, docs/workshop/docs/workshop/Challenge-3-and-4/Challenge-3.md, docs/workshop/docs/workshop/Challenge-5/index.md, docs/workshop/docs/workshop/index.md
Added proper path for all files
added proper path for all files
=> fix: added proper path for all files

src/api/plugins/chat_with_data_plugin.py
This pull request updates the plugin interface methods in `src/api/plugins/chat_with_data_plugin.py` to improve clarity and consistency in naming and descriptions. The changes focus on renaming functions and updating their descriptions to better reflect their purposes.
**Function and API naming improvements:**
* Renamed the kernel function from `ChatWithSQLDatabase` to `GetDatabaseMetrics`, and updated the method name from `get_SQL_Response` to `get_database_metrics` to clarify its purpose as providing quantified results from the database.
* Renamed the kernel function from `ChatWithCallTranscripts` to `GetCallInsights`, updated its description to include "summaries, explanations, and insights," and changed the method name from `get_answers_from_calltranscripts` to `get_call_insights` for …
=> refactor: Rename kernel functions for clarity and consistency

src/api/plugins/chat_with_data_plugin.py
Reverts microsoft/Conversation-Knowledge-Mining-Solution-Accelerator#577
=> revert: "refactor: Rename kernel functions for clarity and consistency"

infra/main.bicep, infra/main.json
This pull request updates the infrastructure deployment templates to improve region validation, update resource URLs, and correct dependencies in the deployment order. The most significant changes are grouped below:
**Region validation and configuration:**
* Added an `@allowed` list for the `location` parameter in `infra/main.bicep` to restrict deployments to a specific set of Azure regions.
* Updated the `aiServiceLocation` parameter in `infra/main.json` to include an `allowedValues` array matching the allowed regions in the Bicep file.
**Resource URL updates:**
* Changed the `baseUrl` variable in both `infra/main.bicep` and `infra/main.json` to point to the `main` branch instead of `dev` for the GitHub raw content source. [[1]](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7 …
=> chore: update allowed regions and baseURL

infra/main.bicep, infra/main.parameters.json, infra/main.waf.parameters.json
* This pull request introduces a dedicated user-assigned managed identity for backend SQL operations and updates the deployment scripts and configuration to use this new identity. It also adds new parameters for the OpenAI API version and model version in the infrastructure parameter files. The main changes are grouped as follows:
**SQL User Assigned Identity and Permissions:**
* Added a new user-assigned managed identity (`sqlUserAssignedIdentity`) specifically for SQL operations, with limited permissions (`db_datareader`, `db_datawriter`).
* Introduced a deployment script module (`createSqlUserAndRole`) to create a SQL user and assign the defined roles to the new managed identity.
* Updated backend configuration and outputs to use the new `sqlUserAssignedIdentity` instead of the …
=> feat: Create User Assigned Identity for SQL DB with Specified Access

.github/workflows/deploy-KMGeneric.yml
This pull request makes a small update to the deployment workflow configuration. The change standardizes and clarifies the parameter names used when deploying resources with the Azure CLI, ensuring consistency across the deployment process. 
- Deployment parameter updates:
* In `.github/workflows/deploy-KMGeneric.yml`, the `az deployment group create` command now uses `location` and `aiServiceLocation` parameters instead of the previous `azureAiServiceLocation` and adds an explicit `location` parameter to align with the expected infrastructure template inputs.
* ...
=> ci: fix deployment pipeline
