microsoft/Conversation-Knowledge-Mining-Solution-Accelerator

.github/workflows/docker-azure-function.yml, .github/workflows/docker-image-web-ui.yml
This commit modifies the permissions of the GITHUB_TOKEN for two GitHub Action workflows in the repository. The GITHUB_TOKEN is a special token that GitHub creates to authenticate GitHub Actions which by default has read/write access across several features of the repository.
The workflows only need 'contents: read' permission, which lets the GITHUB_TOKEN read the repo files during the action "actions/checkout@v2". This change addresses compliance with the [GitHub Action Permission Changes](https://docs.opensource.microsoft.com/github/apps/permission-changes/) by applying the least privilege principle. It reduces the risk of exposing or abusing the token, and helps in protecting the integrity of the repository and its contents.
=> Update Workflow Permissions to apply least privilege principle

infrastructure/ARM/deployment-template.json
Due to the recent update in the Ingestion Client and ArmTemplateBatch.json, CKM V1 got impacted. 
Need to add the variable ('CompletedServiceBusConnectionString') into Deployment json to fix this.
=> Bug-5166-v1-Deploy_issue fixed

GBB.ConversationalKM.WebUI/CognitiveSearch.UI/Views/Home/Index.cshtml, GBB.ConversationalKM.WebUI/README.md, README.md
I'm just pulling this repo and investigating it and I noticed some broken image links and that the product still has the old "Azure Cognitive Search" rather than the new marketing name "Azure AI Search" name.
=> Product name update

GBB.ConversationalKM.WebUI/CognitiveSearch.UI/Search/DocumentSearchClient.cs, infrastructure/ARM/deployment-template.json
Below file got removed/updated 2 weeks back in AzureSamples/CognitiveSearchServices SDK. So, updated
from /Setup/ArmTemplateBatch.json to ingestion-client/infra/main.json.
=> fix: Linked Template for Cognitive Serach Services ARMTemplate json link updated and logic for isPathBase64Encoded updated

.github/workflows/docker-build-push.yml, App/WebApp.Dockerfile, App/app.py
This pull request includes changes to improve the handling of static files in the web application by modifying the Dockerfile and the Flask application routes. The most important changes include copying static files from the frontend build to a new directory and updating the routes to serve these files from the new location.
Changes to static file handling:
* [`App/WebApp.Dockerfile`](diffhunk://#diff-ff4d0d5289f1ee3040858b1baa9a2a1d826b831f535768c69d58a53aca17f195R37-R38): Added commands to copy `index.html` and `favicon.ico` from the frontend build to the `/usr/src/app/static/` directory.
* [`App/app.py`](diffhunk://#diff-3e68efe54582d91430071eeeaad0acfe073c033f1caf41615c131bbd88eb5c9cL37-R54): Updated the `serve_index` and `favicon` routes to serve files from the `static` directory …
=> fix: Dockerfile issue

.github/workflows/deploy.yml
Changed the trigger branch name in deploy.yml from main to ckm-v2.
* This pull request includes a change to the deployment workflow configuration in the `.github/workflows/deploy.yml` file. The change updates the branch name for the deployment validation.
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L5-R5): Changed the branch for the `push` event from `main` to `ckm-v2`.
* ...
=> ci: Update trigger branch in deploy.yml to ckm-v2

Deployment/scripts/index_scripts/process_data.py
* This pull request includes a small change to the `Deployment/scripts/index_scripts/process_data.py` file. The change removes an unnecessary sleep call from the `get_details` function to improve the script's efficiency.
* [`Deployment/scripts/index_scripts/process_data.py`](diffhunk://#diff-4e70f74e980929a9b92eff3e3533bc47afd2932ae504c20b3fb34e01d2ce20caL386): Removed `time.sleep(4)` to avoid unnecessary delay in the script execution.
* Removed the sleep time for KM generic deployment
* Yes
=> fix: Removed time.sleep(4) to avoid unnecessary delay in the script

src/App/frontend/src/chartComponents/HorizontalBarChart.tsx
Tooltips Persist on Bar Chart Until Page Refresh After Response Generation
Tooltips remain on the chart, creating multiple prints, and are only removed upon a full-page refresh.
=> fix: tooltip issue fixed on hover

infra/deploy_ai_foundry.bicep, infra/deploy_app_service.bicep, infra/deploy_azure_function_charts.bicep, infra/deploy_azure_function_rag.bicep, infra/main.bicep, infra/main.json
This pull request includes several changes to the infrastructure deployment scripts, mainly focusing on the management of storage account names and enhancing the configuration of Azure resources. The most important changes include adding new output parameters, updating resource configurations, and removing redundant storage account definitions.
[Bug 14635](https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/14635): [BugBash] - Feedback - KM Generic- App Service to have Always On
[Bug 14639](https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/14639): [BugBash] - Feedback - KM Generic- Need two storage accounts instead of four storage accounts
* Added `storageAccountName` as an output parameter in `infra/deploy_ai_foundry.bicep` and passed it to other modules 
* …
=> fix: Use aifoundry storage account for functionapps

.devcontainer/devcontainer.json, README.md, infra/deploy_ai_foundry.bicep, infra/deploy_cosmos_db.bicep, infra/main.bicep, infra/main.json
This pull request includes several changes across multiple files to update configurations and improve security. The most important changes include updating the environment name length, modifying admin user settings, and changing authentication settings.
[Bug 14684](https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/14684): [GitHub] [#248] - Bug - KM Generic- Resource name too long / env name 10 characters constraint is too low
[Bug 14683](https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/14683): [BugBash] - Feedback - KM Generic- Policy violation for CosmosDB and ACR
[Bug 14682](https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/14682): [GitHub] [#247] - Bug - KM Generic- MacOS Dev Container configuration requires 8gb of RAM, more than my …
=> fix: Automatic pulling latest code from repo, Policy violation for CosmosDB and ACR, env name max 20 characters limit

infra/scripts/add_user_scripts/create-sql-user-and-role.ps1
This pull request includes a small change to the `infra/scripts/add_user_scripts/create-sql-user-and-role.ps1` file. The change ensures that the `sp_addrolemember` command is executed even if the user already exists.
* [`infra/scripts/add_user_scripts/create-sql-user-and-role.ps1`](diffhunk://#diff-db38659ac3a9761c5312f22f21d3cc6ec123558ac0bac26bbca5e66341b15b34L61-R62): Moved the `sp_addrolemember` command outside of the conditional block to ensure it runs regardless of whether the user already exists.
* ...
* ...
=> fix: Always execute sp_addrolemember in create-sql-user-and-role.ps1

.github/workflows/deploy-KMGeneric.yml, README.md, docs/CustomizingAzdParameters.md, infra/deploy_ai_foundry.bicep, infra/main.bicep, infra/main.bicepparam, infra/main.json
This pull request includes changes to update the location for the Content Understanding service and to rename the `gptModelVersion` parameter to `azureOpenAIApiVersion` across multiple files. The most important changes include updates to the deployment scripts, documentation, and infrastructure files.
* [`.github/workflows/deploy-KMGeneric.yml`]: Changed `contentUnderstandingLocation` from `westus` to `swedencentral`.
* [`README.md`]: Updated the default value for `Content Understanding Location` from `West US` to `Sweden Central`.
* [`docs/CustomizingAzdParameters.md`]: Updated allowed values for `Content Understanding Location` and example command to use `swedencentral`.
* [`infra/main.bicepparam`]: Updated `contentUnderstandingLocation` default value to `swedencentral`.
* …
=> fix: Update Content Understanding Service Location & Rename gptModelVersion to azureOpenAIApiVersion Across Files

azure.yaml
This pull request includes significant changes to the `azure.yaml` file for the `conversation-knowledge-mining` configuration. The changes primarily involve the removal of parameters and deployment configuration.
Key changes:
* Removed `parameters` section, including `solutionPrefix`, `otherLocation`, and `baseUrl` definitions.
* Removed `deployment` section, including the mode, template path, and parameter mappings.
=> fix: Remove parameters and deployment configuration in  azure.yaml 

azure.yaml
This pull request includes a significant change to the `azure.yaml` file, specifically the removal of several parameters and the deployment section. Below is a summary of the most important changes:
Configuration simplification:
* [`azure.yaml`](diffhunk://#diff-1ba5bd52036276068bc787a1be3dfa49aa920317ab02fa460c99246a78e588f3L11-L29): Removed the `parameters` section, which included `solutionPrefix`, `otherLocation`, and `baseUrl` settings.
* [`azure.yaml`](diffhunk://#diff-1ba5bd52036276068bc787a1be3dfa49aa920317ab02fa460c99246a78e588f3L11-L29): Removed the `deployment` section, which defined the deployment mode and template path, along with the parameters for the deployment.
=> fix: remove parameters and the deployment section in azure.yaml

docs/quota_check.md, infra/deploy_app_service.bicep, infra/main.json, src/App/WebApp.Dockerfile
This pull request includes changes to documentation and infrastructure configuration to improve the deployment process and update resource specifications.
* [`docs/quota_check.md`](diffhunk://#diff-e017fb8974388f6f46533aad2e78f0f491aa0b3dc6885732e264562e8a55f16bR5-R9): Added instructions for logging in with Azure CLI before deploying the accelerator.
* [`infra/deploy_app_service.bicep`](diffhunk://#diff-37c8b5694d17291d641a19fb8a562e30642066b4bf8b8657f2636f50567cf4ebL23-R23): Changed the `HostingPlanSku` parameter from `P0v3` to `B2` to update the app service plan.
* [`infra/main.json`](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L7-R8): Updated the Bicep generator version from `0.33.93.31351` to `0.34.44.8038` and modified multiple template hashes …
=> fix: Improve Deployment Process with Documentation and Hosting Plan Updates

src/App/src/components/Chat/Chat.tsx
The chat box should be disabled for next question, or the question should not get removed when the response is getting generated for first question. (by User/Customer POV Second solution is more reliable. consider 2nd one)
- in chat box ask question: "Give a summary of billing issues"
- Now when response is generating simply type another question in the chatbot, don't enter/send it. 
- Observe that, the 2nd question that we typed in chatbot will get removed automatically, when the response for first question is still getting generated. 
- Adding video as a reference in the attachment section
=> fix:  While the response is getting generated, question typed in chatbox is getting removed automatically.

docs/quota_check.md, infra/scripts/checkquota_km.sh, infra/scripts/quota_check_params.sh
* ...
This pull request includes updates to the documentation and scripts related to quota checking for Azure services. The changes enhance the clarity of the documentation and improve the efficiency of the scripts.
Documentation updates:
* [`docs/quota_check.md`](diffhunk://#diff-e017fb8974388f6f46533aad2e78f0f491aa0b3dc6885732e264562e8a55f16bL66-R75): Added a step to log in to Azure before navigating to the `scripts` folder and adjusted subsequent step numbers accordingly. [[1]](diffhunk://#diff-e017fb8974388f6f46533aad2e78f0f491aa0b3dc6885732e264562e8a55f16bL66-R75) [[2]](diffhunk://#diff-e017fb8974388f6f46533aad2e78f0f491aa0b3dc6885732e264562e8a55f16bL80-R90)
Script improvements:
* [`infra/scripts/checkquota_km.sh`](diffhunk://#diff-08eea3188bc57fa228d942aa714a2139560e674c06f1aa5dd4da3 …
=> fix: replace standard with globalstandard and updated quota check document

infra/deploy_backend_docker.bicep, infra/main.bicep, infra/main.json, src/api/ApiApp.Dockerfile, src/api/common/config/config.py, src/api/plugins/chat_with_data_plugin.py, src/api/services/chat_service.py
This pull request includes significant changes to the infrastructure deployment scripts and the backend configuration. The key changes involve removing the dependency on Azure Key Vault for secret management and updating the Dockerfile for the API application.
* [`infra/deploy_backend_docker.bicep`](diffhunk://#diff-7934b4de99efd4cba4578f74c59fefa78d390bdac7b0037b19300f96361c4db1R7-L8): Added new secure parameters for `azureOpenAIKey`, `azureAiProjectConnString`, and `azureSearchAdminKey`, and removed the `keyVaultName` parameter. Updated the `appService` module to use these new parameters. [[1]](diffhunk://#diff-7934b4de99efd4cba4578f74c59fefa78d390bdac7b0037b19300f96361c4db1R7-L8) [[2]](diffhunk://#diff-7934b4de99efd4cba4578f74c59fefa78d390bdac7b0037b19300f96361c4db1R92-R94)
* …
=> fix: Removing the dependency on Azure Key Vault & Truncate SQL response

infra/deploy_backend_docker.bicep, infra/main.bicep, infra/main.json, src/api/ApiApp.Dockerfile, src/api/common/config/config.py, src/api/plugins/chat_with_data_plugin.py, src/api/requirements.txt, src/api/services/chat_service.py
This pull request includes several changes to the infrastructure and API services, primarily focusing on integrating AI project functionality and updating dependencies. The most important changes include adding AI project parameters, updating role assignments, and modifying the chat service to use the new AI agent.
* [`infra/deploy_backend_docker.bicep`](diffhunk://#diff-7934b4de99efd4cba4578f74c59fefa78d390bdac7b0037b19300f96361c4db1R14): Added `aiProjectName` parameter and resources for AI project and developer access. [[1]](diffhunk://#diff-7934b4de99efd4cba4578f74c59fefa78d390bdac7b0037b19300f96361c4db1R14) [[2]](diffhunk://#diff-7934b4de99efd4cba4578f74c59fefa78d390bdac7b0037b19300f96361c4db1R122-R138)
* [`infra/main.bicep`](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7 …
=> feat: Use AI agent with plugins

infra/deploy_keyvault.bicep, infra/main.json
This pull request makes changes to the Key Vault configuration in the Bicep and JSON deployment templates. The most significant update is the removal of the `enablePurgeProtection` property from the Key Vault configuration, along with updates to the template hash values in the generated JSON files.
* Removed the `enablePurgeProtection` property from the Key Vault configuration in `deploy_keyvault.bicep` and `main.json`. This change may affect the ability to recover deleted Key Vaults or their contents. [[1]](diffhunk://#diff-82312b3acfa82a4f0980d7e0592f22b8db36f98965a61c340510f972ad7306faL39) [[2]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L298)
* Updated the `templateHash` values in `infra/main.json` to reflect changes in the generated deployment …
=> fix: disable purge protection of key vault

src/App/src/components/Chat/Chat.tsx, src/api/plugins/chat_with_data_plugin.py
This pull request introduces a couple of key improvements to error handling and response optimization in the chat application. Specifically, it ensures database updates are not attempted when an error message is present and limits the size of citation content in API responses to reduce load.
* [`src/App/src/components/Chat/Chat.tsx`](diffhunk://#diff-a8495413a74092724ad57e37fffa0de07c14fc3a4c605214fe3dcb5ea062f67fR645-R647): Added a check to prevent saving messages to the database if an error message is present in the `updatedMessages` array. This ensures that only valid messages are persisted.
* [`src/api/plugins/chat_with_data_plugin.py`](diffhunk://#diff-b27470a6fea7b89bec4be004dcebd0866befdbd90d775b9782006ee9c155afa1R201-R206): Added logic to truncate citation content to 300 …
=> fix: Limiting citation content length in kernel function responses and restrict save history for error response

src/App/src/App.tsx, src/App/src/components/ChatHistoryListItemCell/ChatHistoryListItemCell.tsx, src/App/src/components/Citations/Citations.tsx, src/App/src/state/AppProvider.tsx, src/App/src/state/AppReducer.tsx
Citation remains open even after deleting complete chat history
Deploy KM Generic
Generate chat history, ask such question, where in response you will get some citations. (ask questions from below list.)
Total number of calls by date for last 7 days
Generate Chart
Show average handling time by topics in minutes
What are top 7 challenges user reported
Give a summary of billing issues
When customers call in about unexpected charges, what types of charges are they seeing?
Open any citation link, open Chat history panel as well, now total 4 sections are open
In chat history delete complete chat history
Observe that opened citation remains open.
=> fix: citation remains open even after deleting complete chat history 

src/App/src/components/Chat/Chat.tsx
If starting a new chat, citation panel should get closed automatically.
- Deploy KM Generic
- Create Chat history
- Open a chat history from which open a citation link (citation panel will be opened)
- now click on new chat, (+ icon)
- Citation panel should get closed.
=> fix: If starting a new chat, citation panel should get closed automatically.

src/App/.dockerignore, src/App/WebApp.dockerignore, src/api/.dockerignore, src/api/ApiApp.dockerignore
- This PR renames WebApp.dockerignore and ApiApp.dockerignore to .dockerignore so they are properly recognized by the Docker CLI during image builds.
- It also expands the ignore rules to exclude unnecessary files and directories (such as node_modules, .venv, IDE configs, and logs) from being sent to the Docker daemon.
- This helps improve build performance, reduce image size, and prevent accidental inclusion of development or sensitive files in the container image.
Verify that the following are valid:
- Verify that the renamed .dockerignore file is present at the appropriate root level for both WebApp and ApiApp contexts.
- Confirm that the old WebApp.dockerignore and ApiApp.dockerignore files have been removed.
- Check that the new .dockerignore includes all relevant patterns to exclude …
=> build: Refactor and Standardize .dockerignore Files Across ApiApp and WebApp

src/App/src/components/Chat/Chat.tsx
Chat History Fails to Save After Receiving Error (e.g., Rate Limit Error), Even When Valid Response is Received Afterwards
- Deploy KM Generic
- Open application
- Once dashboard loads properly
- Ask some questions in chat: "Total number of calls by date for last 7 days"
- After asking few questions you may receive an error message saying: "Rate limit exceeded. Try again in 7 seconds"
- Ask the same question again: "Total number of calls by date for last 7 days"
- After you get the proper response just refresh the page and open the chat history thread for this previous chat. 
- Observe and verify if chat history is getting saved or not?
- If it's getting saved, check if there is history for question asked after the Error message or not.
=> fix: Chat History Fails to Save After Receiving Error (e.g., Rate Limit Error), Even When Valid Response is Received Afterwards

src/App/.dockerignore
This pull request makes updates to the `.dockerignore` file in the `src/App` directory to refine the list of ignored files and directories. The primary change is the removal of `.env` from the ignore list.
Updates to `.dockerignore`:
* Removed `.env` from the ignore list in the root section of the `.dockerignore` file. This change ensures that `.env` files are no longer excluded from Docker build contexts.
* Removed `.env` from the "Environments" section of the `.dockerignore` file, aligning with the decision to include `.env` files in Docker operations.
=> fix:  Removal of App `.env` from the ignore list

src/App/src/App.tsx
Citation panel remains visible after hiding chat
1. Navigate to the KM Generic web application.
2. Interact with the chat by asking a few questions until citation links appear.
3. Click on any citation link to open the citation panel.
4. Click the "Hide Chat" button.
=> fix: Hide citation panel logic on click of hide chat

infra/main.bicep, infra/main.json
This pull request includes changes to update the `baseUrl` used in deployment scripts and adjusts the `templateHash` in the JSON configuration file. The changes ensure compatibility with the main branch of the repository and reflect updates to the template version.
* [`infra/main.bicep`](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L68-R68): Changed the `baseUrl` to point to the main branch of the repository instead of the previous `psl-pk-aifoundryresource` branch.
* [`infra/main.json`](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L343-R343): Updated the `baseUrl` to match the new main branch URL, ensuring consistency across deployment configurations.
* [`infra/main.json`](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5 …
=> fix: Point baseurl to main branch

src/tests/api/plugins/test_chat_with_data_plugin.py, src/tests/api/services/test_chat_service.py, src/tests/api/services/test_history_service.py
This pull request refactors test cases across multiple files to replace direct imports of `Config` and `get_bearer_token_provider` with their counterparts in `helpers.azure_openai_helper`. Additionally, it introduces mock configuration instances to simulate Azure OpenAI settings in tests, ensuring consistency and modularity in the test setup.
* [`src/tests/api/plugins/test_chat_with_data_plugin.py`](diffhunk://#diff-704d83d8eb40fb5a0d85ecaee5d58e9f10d32c4ba550b1791732e2c566d44aa2L28-R40): Replaced imports of `Config` and `get_bearer_token_provider` with `helpers.azure_openai_helper.Config` and `helpers.azure_openai_helper.get_bearer_token_provider` across multiple test cases. Mock configuration instances were introduced to simulate Azure OpenAI endpoint and API version settings. …
=> fix: fix unittestcases

azure.yaml, infra/scripts/docker-build.ps1, infra/scripts/docker-build.sh
This pull request introduces support for specifying a custom image tag (`AZURE_ENV_IMAGETAG`) during the Docker build and push process. The changes ensure that this new parameter is optional, defaulting to `latest` if not provided, and propagate it through the relevant scripts and configuration files.
* **Added `AZURE_ENV_IMAGETAG` Parameter**:
- Updated `infra/scripts/docker-build.ps1` and `infra/scripts/docker-build.sh` to accept an additional parameter, `AZURE_ENV_IMAGETAG`, for specifying a custom Docker image tag. This parameter defaults to `latest` if not provided. [[1]](diffhunk://#diff-bbd8ac6fc2f33cfdb70dd2aad3a606da6e0dae8518301f42797c548c040a9939L7-R20) [[2]](diffhunk://#diff-56125c9f69919272261971d188ab641a2ccaa992f4bd2750e78f66ba3aac1577R10-R14) …
=> fix: Can't use custom image tag with USE_LOCAL_BUILD=true

infra/deploy_ai_foundry.bicep, infra/main.json, infra/scripts/index_scripts/02_create_cu_template_audio.py, infra/scripts/index_scripts/02_create_cu_template_text.py, infra/scripts/index_scripts/03_cu_process_data_text.py, infra/scripts/index_scripts/04_cu_process_data_new_data.py
This pull request removes the use of the `AZURE-OPENAI-CU-KEY` secret across the infrastructure and scripts, simplifying the configuration and authentication process. The changes primarily involve the removal of references to this key in both the infrastructure deployment files and Python scripts.
* Removed the `azureOpenAICUApiKeyEntry` resource from `infra/deploy_ai_foundry.bicep`, which previously stored the `AZURE-OPENAI-CU-KEY` secret in Azure Key Vault.
* Deleted the corresponding `AZURE-OPENAI-CU-KEY` secret configuration in `infra/main.json`, including its dependencies and references.
* Updated template hash values in `infra/main.json` to reflect changes in the Bicep and JSON templates. [[1]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L8-R8) …
=> fix: removes the use of the `AZURE-OPENAI-CU-KEY` secret across the infrastructure and scripts

.github/workflows/deploy-KMGeneric.yml, .github/workflows/docker-build.yml, src/api/agents/conversation_agent_factory.py, src/api/agents/search_agent_factory.py, src/tests/api/agents/test_search_agent_factory.py
This pull request introduces updates to workflows and agent configurations to improve naming conventions and streamline deployment processes. Key changes include updates to Docker tag naming, adjustments to Azure AI agent names, and modifications to indexing configurations.
* [`.github/workflows/deploy-KMGeneric.yml`](diffhunk://#diff-d89c1a2a54c3fecc22cbfae6dc62ebdfeb753cd82c7192b447c07e8235242d75L123): Removed an unnecessary line break in the deployment command parameters to streamline the syntax.
* [`.github/workflows/docker-build.yml`](diffhunk://#diff-3414847e2ad632333f775cabb810f0dc0df61a570365df34750a08b00912fe82L52-R52): Updated the Docker tag naming convention for the `main` branch to use `latest_fdp` instead of `latest`.
* …
=> fix: Refactor agent names and index identifiers for KM alignment and improved uniqueness

.github/workflows/deploy-KMGeneric.yml, infra/main.json
* ...
This pull request updates the `bicep` generator version and associated template hashes in the `infra/main.json` file. The changes ensure compatibility with the newer version of the `bicep` tool and reflect updated template metadata.
Key changes:
* Updated the `bicep` generator version from `0.36.1.42791` to `0.36.177.2456` across all instances in the `infra/main.json` file. This update aligns the infrastructure code with the latest version of the `bicep` tool. [[1]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L7-R8) [[2]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L415-R416) [[3]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L526-R527) …
=> fix: updated main json

infra/deploy_ai_foundry.bicep, infra/deploy_backend_docker.bicep, infra/deploy_foundry_role_assignment.bicep, infra/main.json
This pull request refines the role assignment logic and resource definitions in the Bicep files for AI Foundry and Backend Docker deployments. The changes primarily focus on improving modularity, handling scenarios with or without system-assigned identities, and supporting AI model deployments.
* Updated `infra/deploy_ai_foundry.bicep` to differentiate between existing AI projects and new ones by creating separate modules and resources for role assignments based on the presence of `azureExistingAIProjectResourceId`. This ensures better handling of existing AI project configurations. [[1]](diffhunk://#diff-801321770c4260aea129a24ab905704034ec515f2811ee5d93a6fc7c2d29c626L253-R265) [[2]](diffhunk://#diff-801321770c4260aea129a24ab905704034ec515f2811ee5d93a6fc7c2d29c626L282-R302)
* Added …
=> fix: Model Deployment When Reusing Existing Foundry Projects

src/api/common/database/sqldb_service.py
This pull request introduces a minor update to the `get_db_connection` function in `src/api/common/database/sqldb_service.py`. The change enhances the function to use a `client_id` for the `ManagedIdentityCredential`, improving the configuration flexibility.
* [`src/api/common/database/sqldb_service.py`](diffhunk://#diff-a4829106285a4d5ecc980ddbc6392e949639599ed516c0b2b3d42b24244da2aaR21-R24): Added a `mid_id` variable to retrieve the `client_id` from the configuration and updated the `ManagedIdentityCredential` instantiation to use `client_id=mid_id`.
=> fix: Use ManagedIdentityCredential with Configurable Client ID

docs/workshop/docs/workshop/Challenge-5/python/content_understanding_client.py, infra/scripts/index_scripts/azure_credential_utils.py, infra/scripts/index_scripts/content_understanding_client.py, src/api/helpers/azure_credential_utils.py, src/tests/api/helpers/test_azure_credential_utils.py
This pull request updates the Azure credential logic across several scripts and modules to use `AzureCliCredential` instead of `DefaultAzureCredential` for development environments. It also updates related tests and documentation to reflect this change, ensuring consistency and clarity throughout the codebase. Additionally, some minor cleanups were made to remove unnecessary comments.
**Azure Credential Logic Updates:**
* Switched development environment credential from `DefaultAzureCredential` to `AzureCliCredential` in `src/api/helpers/azure_credential_utils.py` and its async variant, as well as in `infra/scripts/index_scripts/azure_credential_utils.py`. All type hints, docstrings, and credential returns were updated accordingly. …
=> refactor: Credential Handling: Replace DefaultAzureCredential with AzureCliCredential

infra/main.bicep, infra/main.json, src/start.cmd, src/start.sh
* This pull request introduces significant improvements to the Azure infrastructure deployment scripts, focusing on standardizing parameter names, supporting resource tagging, and enhancing output variables for better integration and management. The changes primarily update the Bicep templates and deployment workflows to align with best practices, improve maintainability, and provide more flexibility for resource configuration.
**Key changes include:**
- Standardized parameter names across Bicep modules (e.g., `solutionName`, `hostingPlanName`, `websiteName`) and added descriptions to improve clarity and consistency in `infra/deploy_ai_foundry.bicep`, `infra/deploy_app_service.bicep`, and related files. [[1]](diffhunk://#diff-801321770c4260aea129a24ab905704034ec515f2811ee5d93a6fc7c2d29c626 …
=> feat: KMGenric Bicep Standard Changes (output vars changed to caps)

.devcontainer/setup_env.sh
This pull request makes a minor update to the `.devcontainer/setup_env.sh` script by removing commands that set executable permissions for two Docker build scripts. This change likely reflects that these scripts are no longer needed or have been relocated.
* Removed `chmod +x` commands for `docker-build.sh` and `docker-build.ps1` in `.devcontainer/setup_env.sh`, indicating these scripts are no longer part of the setup process.
=> fix: remove unused files from setup_env.sh

.github/workflows/deploy-KMGeneric.yml, infra/deploy_app_service.bicep
This pull request updates the deployment workflow and related infrastructure configuration to improve branch handling, deployment tagging, and resource tagging. The changes enhance how branch names are determined during workflow runs, simplify tag assignment logic, and add a security tag to deployments.
**Workflow improvements:**
* Updated the `BRANCH_NAME` environment variable in `.github/workflows/deploy-KMGeneric.yml` to use `github.event.workflow_run.head_branch` as the primary source, falling back to other branch references for more robust branch detection during workflow runs.
**Deployment logic simplification:**
* Simplified the tag assignment logic in the `Determine Tag Name Based on Branch` step, ensuring that branches not explicitly handled default to `latest_fdp` instead of …
=> ci: fix deployment pipeline

infra/scripts/run_process_data_scripts.sh
This pull request makes a targeted improvement to the way managed identities are selected in the `infra/scripts/run_process_data_scripts.sh` script. Specifically, it refines the filtering logic to exclude identities with names starting with `id-sql-`, ensuring only the intended identities are used.
Identity selection logic update:
* Updated the queries for both `managedIdentityResourceId` and `managedIdentityClientId` to exclude user-assigned identities whose names start with `id-sql-`, preventing accidental selection of SQL-related managed identities. [[1]](diffhunk://#diff-16bab50f8dd1b70d78f1df0136ae064e15a39829379e51e317f28f7138ca4897L28-R28) [[2]](diffhunk://#diff-16bab50f8dd1b70d78f1df0136ae064e15a39829379e51e317f28f7138ca4897L37-R37)
Verify custom data processing.
=> fix: Custom data processing - Exclude SQL user-assigned identities from identity retrieval query
